language: python

python: 2.7

env:
  - TOXENV=py32-django17
  - TOXENV=py32-django18
  - TOXENV=py32-django_trunk
  - TOXENV=py33-django17
  - TOXENV=py33-django18
  - TOXENV=py33-django_trunk
  - TOXENV=py34-django17
  - TOXENV=py34-django18
  - TOXENV=py34-django_trunk

install:
  - pip install --upgrade pip setuptools tox virtualenv coveralls

script:
  - tox

matrix:
  allow_failures:
    - env: TOXENV=py32-django_trunk
    - env: TOXENV=py33-django_trunk
    - env: TOXENV=py34-django_trunk

after_success: coveralls

